# -*- coding: utf-8 -*-
"""Playlist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RrWMnkkSd_-sufMoPVhoDFSqin5Fu9UM

Import .py souboru v Google Colaboratory
"""

from Kostka.playlist_50_songs import playlist


print(len(playlist))  # počet písní
print(playlist[:5])   # prvních 5 písní

"""Program nabídne menu:

1️⃣ Přidat novou píseň (uživatel zadá jméno, interpreta, délku).

2️⃣ Odebrat píseň podle názvu.

3️⃣ Zobrazit celkovou délku playlistu.

4️⃣ Vypsat unikátní interprety (set).

5️⃣ Seřadit podle délky nebo podle názvu.
"""

playlist.append(('Madonna','Frozen',4))
playlist[-1]

"""Odebere písně interpreta"""

playlist_filtered = [song for song in playlist if song[0] != "Taylor Swift"]
print(playlist_filtered)

for i in range(len(playlist) - 1, -1, -1):  # projdeme seznam pozpátku
    if playlist[i][0] == "Madonna":
        del playlist[i]

# kontrola výsledku
print("Počet písní po odebrání Queen:", len(playlist))
print("Aktuální playlist:", playlist)

"""Zobrazit celkovou délku playlistu"""

total_length = 0
for song in playlist:
    total_length += song[2]  # třetí prvek n-tice je délka v minutách

print(f"Celková délka playlistu: {total_length:.0f} minut")

"""Seznam unikátních interpretů"""

unique_artists = set()
for song in playlist:
    unique_artists.add(song[0])  # první prvek n-tice je interpret

# výpis
print("Unikátní interpreti:")
for artist in unique_artists:
    print(artist)

"""Seřadit podle délky"""

# seřazení playlistu podle délky písní (od nejkratší po nejdelší)
playlist.sort(key=lambda song: song[2])

# výpis prvních 5 písní pro kontrolu
print("5 nejkratších písní v playlistu:")
for song in playlist[:5]:
    print(f"{song[0]} – {song[1]} ({song[2]} min)")